name = "millers-cafe-site"
compatibility_date = "2026-02-17"
pages_build_output_dir = "."

# Static site at repository root, with Pages Functions in /functions.

[[kv_namespaces]]
binding = "BOOKINGS_KV"
id = "03f49e1de7d4404192bfe6856f518157"
preview_id = "2777eb98b74e45e3a6edf8c953836da2"

[vars]
BOOKINGS_NOTIFICATION_EMAIL = "help@millers.cafe"
BOOKINGS_REPLY_TO = "help@millers.cafe"
BOOKINGS_EMAIL_FROM = "Millers Cafe <help@millers.cafe>"
